# Generated by Django 4.2.1 on 2024-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_project_users_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor_users',
            field=models.ManyToManyField(related_name='projects', to='Api.user'),
        ),
    ]
